// src/components/member/MemberAvatar.tsx
import { memo } from 'react'
import { getHashColor } from '../../utils/hash-color'
import type { AvatarSize } from '../../types'

interface Props {
  name: string
  avatar?: string
  size?: AvatarSize
  className?: string
  style?: React.CSSProperties
}

const sizeMap = {
  sm: 'w-8 h-8 text-xs',
  md: 'w-12 h-12 text-sm',
  lg: 'w-16 h-16 text-lg',
}

export const MemberAvatar = memo(function MemberAvatar({ name, avatar, size = 'sm', className = '', style }: Props) {
  const sizeClass = sizeMap[size]
  const imgSize = sizeClass.split(' ').slice(0, 2).join(' ')

  if (avatar) {
    return (
      <img
        src={avatar}
        alt={name}
        className={`rounded-full object-cover shrink-0 ${imgSize} ${className}`}
        loading="lazy"
        style={style}
      />
    )
  }

  const colorClass = getHashColor(name)
  const initial = name.charAt(0)

  return (
    <div className={`rounded-full shrink-0 flex items-center justify-center font-medium text-white/90 ${sizeClass} ${colorClass} ${className}`} style={style}>
      {initial}
    </div>
  )
})

// src/components/MemberAvatar.vue
<script setup lang="ts">
const props = defineProps<{
  name: string
  avatar?: string
  size?: 'sm' | 'md' | 'lg'
}>()

const initial = props.name.charAt(0)

// 이름 기반 고정 색상 (같은 이름이면 항상 같은 색)
const colors = [
  'bg-[#5B21B6]', 'bg-[#1E40AF]', 'bg-[#065F46]',
  'bg-[#92400E]', 'bg-[#7C2D12]', 'bg-[#4C1D95]',
  'bg-[#1E3A5F]', 'bg-[#3730A3]', 'bg-[#6B21A8]',
  'bg-[#164E63]', 'bg-[#4338CA]', 'bg-[#0F766E]',
  'bg-[#7E22CE]',
]

let hash = 0
for (const ch of props.name) {
  hash = ch.charCodeAt(0) + ((hash << 5) - hash)
}
const colorClass = colors[Math.abs(hash) % colors.length]

const sizeClasses = {
  sm: 'w-8 h-8 text-xs',
  md: 'w-12 h-12 text-sm',
  lg: 'w-16 h-16 text-lg',
}

const sizeClass = sizeClasses[props.size ?? 'sm']
</script>

<template>
  <img
    v-if="avatar"
    :src="avatar"
    :alt="name"
    class="rounded-full object-cover shrink-0"
    :class="sizeClass.split(' ').slice(0, 2).join(' ')"
    loading="lazy"
  />
  <div
    v-else
    class="rounded-full shrink-0 flex items-center justify-center font-medium text-white/90"
    :class="[sizeClass, colorClass]"
  >
    {{ initial }}
  </div>
</template>
